### ISSUE TITLE
Tarea 007. Creación de "enrolment"

### ISSUE THREAD

**Issue by alejandromd** [alejandromd/Acme-L3-D01#29]

**Comment by alejandromd** [comment]
An enrolment is a registration of a student in a course.  The system must store the following data about them: a code (pattern “[A-Z]{1,3}[0-9][0-9]{3}”, not blank, unique), a motivation (not blank, shorter than 76 characters), some goals (not blank, shorter than 101 characters), and a work time (in hours, computed from the corresponding activities).

**Comment by Thealean28** [comment]
Implementada
