### ISSUE TITLE
Tarea 009. Creación de "student dashboard"

### ISSUE THREAD

**Issue by alejandromd** [alejandromd/Acme-L3-D01#31]

**Comment by alejandromd** [comment]
The system must handle student dashboards with the following data: total number of theory and hands-on activities in his or her workbook; average, deviation, minimum, and maximum period of the activities in his or her workbook; average, deviation, minimum, and maximum learning time of the courses in which he or she has enrolled.

**Comment by Thealean28** [comment]
Terminado
